name: Automate Issue Labeling and Project Management

on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Determine sprint label
      run: |
        current_date=$(date +'%Y-%m-%d')
        if [[ "$current_date" > "2025-02-07" && "$current_date" < "2025-03-07" ]]; then
          echo "sprint=sprint-2" >> $GITHUB_ENV
        elif [[ "$current_date" > "2025-03-07" && "$current_date" < "2025-03-21" ]]; then
          echo "sprint=sprint-3" >> $GITHUB_ENV
        elif [[ "$current_date" > "2025-03-21" && "$current_date" < "2025-04-11" ]]; then
          echo "sprint=sprint-4" >> $GITHUB_ENV
        else
          echo "sprint=sprint-1" >> $GITHUB_ENV
        fi

    - name: checkout
        uses: actions/checkout@v3
        
    - name: Label new issue
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: ${{ env.sprint }}

    - name: Move issue to project
      uses: alex-page/github-project-automation-plus@v0.3.0
      with:
        project: 'Project2048 - ChatHaven'
        column: 'Tasks To Do'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
