name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd chathaven &&  npm install
        
      - name: install CRA
        run: cd chathaven && npm install react-scripts

      - name: Run ESLint
        run:  cd chathaven && npx eslint . --ext .js,.jsx,.ts,.tsx || true

      - name: Run Stylelint
        run:  cd chathaven && npx stylelint "**/*.{css,scss}" || true
      - name: Compile Tailwindv4
        run: cd chathaven && npm run tailwindcss-build
        

      - name: Build React App in /chathaven
        working-directory: chathaven
        run: |
          npm install
          CI=false npm run build
        env:
          NODE_ENV: production

      - name: Start Application
        run: npm run start
        env: 
          NODE_ENV: production
