name: Continuous Integration, Delivery and Deployment (CI/CD) Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chathaven
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install CRA
        run: npm ci react-scripts

      - name: Install Serve
        run: npm ci -g serve

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx || true

      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss}" || true
      - name: Run Tailwind CSS
        run: |
          npm install @tailwindcss/cli@4.1.3
          npx @tailwindcss/cli -i ./src/styles/index.css -o ./styles/tailwind.CSS/tailwind.css --minify || true
          npx npx @tailwindcss/cli -i ./src/styles/root_index.css -o ./styles/tailwind.CSS/tailwind.css --minify || true

      - name: Build the project
        run: |
          CI=false 
          npm run build
        env:
          NODE_ENV: production